-- Schema for Sustainability Intelligence Platform
-- Tables: co2_intensity, generation_mix, netzero_alignment

-- 1) CO2 intensity (gCO2/kWh) time-series
create table if not exists public.co2_intensity (
	id bigint generated by default as identity primary key,
	"timestamp" timestamptz not null,
	co2_intensity_g_per_kwh numeric not null
);

-- 2) Generation mix (MW) by technology with renewable share
create table if not exists public.generation_mix (
	id bigint generated by default as identity primary key,
	"timestamp" timestamptz not null,
	hydro_mw numeric not null,
	wind_mw numeric not null,
	solar_mw numeric not null,
	nuclear_mw numeric not null,
	fossil_mw numeric not null,
	total_mw numeric not null,
	renewable_share_pct numeric not null
);

-- 3) Net-zero trajectory alignment per year
create table if not exists public.netzero_alignment (
	"year" int primary key,
	actual_emissions_mt numeric not null,
	target_emissions_mt numeric not null,
	alignment_pct numeric not null
);



